### ISSUE TITLE
在本地地址 http://127.0.0.1/   控制台打印信息怎么清除掉 😢

### ISSUE THREAD

**Issue by xiongwei233** [wangrongding/ding-script#1]
![image](https://user-images.githubusercontent.com/59524219/185778593-1ac2ea0b-9dca-4f5f-b9d6-f6c9ddd81abe.png)

**Comment by wangrongding** [comment]
> ![image](https://user-images.githubusercontent.com/59524219/185778593-1ac2ea0b-9dca-4f5f-b9d6-f6c9ddd81abe.png)

哪个脚本？

**Comment by xiongwei233** [comment]
![Uploading image.png…]()

2.0版本

**Comment by xiongwei233** [comment]
![image](https://user-images.githubusercontent.com/59524219/185779256-6ac990eb-0a20-4bfe-8db3-a6aaccf29f23.png)
